# Generated by Django 3.2 on 2021-05-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earrings', '0006_earring_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earring',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
