# Generated by Django 3.2.3 on 2021-05-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earrings', '0007_alter_earring_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earring',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
