# Generated by Django 3.2.3 on 2021-05-23 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earrings', '0009_auto_20210523_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earring',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='earring',
            name='stock',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)]),
        ),
    ]
