# Generated by Django 3.2.3 on 2021-05-23 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('earrings', '0008_alter_earring_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0002_delete_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('earring_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='earrings.earring')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
