# Generated by Django 3.2 on 2021-05-09 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210509_0349'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collections',
            new_name='Collection',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='collections',
            new_name='collection',
        ),
    ]
